name: "bohr.io deploy"

description: "Deploy your repository on bohr.io"

runs:

  using: "composite"

  steps:

    - name: Checkout Action
      uses: actions/checkout@v3

    - name: Setup node env
      uses: actions/setup-node@v3
      with:
        node-version: "16"

    - name: Deploy on bohr.io
      run: |
        npm i bohr@latest
        npx bohr deploy
      shell: bash