name: "bohr.io deploy"
description: "Deploy your repository on bohr.io"
inputs:
  cli-version:
    description: 'Optional CLI version tag'
    default: 'latest'
    required: false
runs:
  using: "composite"
  steps:

    - name: Setup node env
      uses: actions/setup-node@v3
      with:
        node-version: "16"

    - name: Deploy on bohr.io
      run: npx bohr@${{ inputs.cli-version }} deploy
      shell: bash