name: "bohr.io deploy"
description: "Deploy your repository on bohr.io"
inputs:
  cli-version:
    description: "Optional CLI version"
    required: false
runs:
  using: "composite"
  steps:
    - name: Setup node env
      uses: actions/setup-node@v3
      with:
        node-version: "16"

    - name: Install OIDC Client from Core Package
      run: |
        yarn add @actions/core -W
      shell: bash

    - name: Get ID token from Github OIDC provider
      uses: actions/github-script@v6
      id: get_id_token
      with:
        script: |
          const coreAction = require('@actions/core');
          coreAction.setOutput('id_token', await coreAction.getIDToken());

    - name: Deploy on bohr.io using NPM
      run: |
        yarn add bohr@latest -W
        node_modules/bohr/bin/run deploy
      env:
        ID_TOKEN: ${{ steps.get_id_token.outputs.id_token }}
        GITHUB_TOKEN: ${{ github.token }}
        FORCE_COLOR: "2"
      if: ${{ inputs.cli-version == null }}
      shell: bash

    - name: Deploy on bohr.io [${{ inputs.cli-version }}]
      run: |
        yarn add ${{ inputs.cli-version }} -W
        node_modules/@bohr.io/bohr-dev/bin/run deploy
      env:
        ID_TOKEN: ${{ steps.get_id_token.outputs.id_token }}
        GITHUB_TOKEN: ${{ github.token }}
        FORCE_COLOR: "2"
      shell: bash
      if: ${{ inputs.cli-version != null }}
