name: "bohr.io deploy"
description: "Deploy your repository on bohr.io"
inputs:
  cli-version:
    description: "Optional CLI version"
    required: false
  npm-token:
    description: "Optional NPM token for private CLI version"
    required: false
runs:
  using: "composite"
  steps:
    - name: Setup node env
      uses: actions/setup-node@v3
      with:
        node-version: "16"

    - name: Cache node modules
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: |
          ~/.npm
          /home/runner/.cache
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install OIDC Client from Core Package
      run: npm install @actions/core
      shell: bash

    - name: Get ID token from Github OIDC provider
      uses: actions/github-script@v6
      id: get_id_token
      with:
        script: |
          const coreAction = require('@actions/core');
          coreAction.setOutput('id_token', await coreAction.getIDToken());

    - name: Deploy on bohr.io
      run: npx bohr@latest deploy
      env:
        ID_TOKEN: ${{ steps.get_id_token.outputs.id_token }}
      shell: bash
      if: ${{ inputs.cli-version == null }}

    - name: Set NPM token
      run: |
        npm config set @bohr.io:registry https://registry.npmjs.org
        npm config set //registry.npmjs.org/:_authToken ${{ inputs.npm-token }}
      shell: bash
      if: ${{ inputs.npm-token != null }}

    - name: Deploy on bohr.io [${{ inputs.cli-version }}]
      run: |
        npx ${{ inputs.cli-version }} deploy
      env:
        ID_TOKEN: ${{ steps.get_id_token.outputs.id_token }}
        CLI_VERSION: ${{ inputs.cli-version }}
      shell: bash
      if: ${{ inputs.cli-version != null }}
