name: "bohr.io deploy"
description: "Deploy your repository on bohr.io"
inputs:
  cli-version:
    description: "Optional CLI version"
    required: false
runs:
  using: "composite"
  steps:
    - name: Deploy on bohr.io using NPM
      run: |
        yarn add bohr@latest -W
        node_modules/bohr/bin/run deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}
        FORCE_COLOR: "2"
      if: ${{ inputs.cli-version == null }}
      shell: bash

    - name: Deploy on bohr.io [${{ inputs.cli-version }}]
      run: |
        yarn config set registry http://npm.bohr.io:5000
        yarn add ${{ inputs.cli-version }} -W
        node_modules/@bohr.io/bohr-dev/bin/run deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}
        FORCE_COLOR: "2"
      shell: bash
      if: ${{ inputs.cli-version != null }}
